---
title: "LGH Daily ED visits forecast"
author: "Nayef Ahmad"
date: "May 16, 2019"
output: 
    html_document: 
        toc: true
        code_folding: hide
        toc_depth: 4
        toc_float: 
            collapsed: false
        self_contained: no
editor_options: 
  chunk_output_type: console
fontsize: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)

library(knitr)
library(kableExtra)

library(odbc)
library(dbplyr)
library(magrittr)  
library(tidyverse)
library(here)
library(DT)

# shortcuts: 
# > ctrl + alt + i ==> new code chunk
# > ctrl + shift + k ==> knit doc 
# \  ==> line break (include 2 spaces after)

```

# Setup connection to database: 

```{r denodo-setup}
# Setup connections to denodo and import functions

source(here::here("src",
                  "setup-denodo_function.R"))

setup_denodo()


# Functions to pull ED data, and to forecast future ED visits:
source(here::here("src",
                  "ed-visits-denodo_function.R"))
source(here::here("src",
                  "ed-visits-forecast-denodo_function.R"))





```

\  
\  
\  

# Set forecast dates: 

```{r params}
startdate_id <- "20190901"
enddate_id <- "20191007" 

data.frame(parameter = c("Beginning of fcast interval", 
                         "End of fcast interval"), 
           date = c(startdate_id, 
                    enddate_id)) %>% 
      
      kable() %>% 
      kable_styling(bootstrap_options = c("striped",
                                          "condensed", 
                                          "responsive"))
                                          


```

\  
\  
\  

# Components of the model: 
```{r fcast-and-actuals}
edvisits_fcast <- edvisits_forecast(startdate_id,
                                    enddate_id,
                                    trend_flexibility = 0.05,
                                    past_years = 5, 
                                    save_plots = TRUE,
                                    holidays_df = holidays)

edvisits_actual <- extract_ed_visits(startdate_id,
                                     enddate_id)


```

\  
\  
\  

# Historical data and fitted model: 
```{r}
edvisits_fcast[[2]]
```

\  
\  
\  

# Forecast results: 
```{r display-downloadable-table}
edvisits_fcast[[1]] %>%
  DT::datatable(extensions = 'Buttons', 
                options = list(dom = 'Bfrtip', 
                   buttons = c('excel', "csv"))) %>% 
  formatRound(c("edvisits_fcast", 
                "edvisits_lower_ci", 
                "edvisits_upper_ci"), 
              1)
  
```

\  
\  
\  

# Cross validation 
Results for 24 day forecast horizon: 

* Cross-validated RMSE is **13.3 visits**. 
* Cross-validated MAE is **10.5 visits**. 
* Cross-validated MAPE is **0.060** or **6.0%**. 

```{r cross-validate, eval=FALSE}

# Warning: this will take a very long time to run

m <- edvisits_fcast[[5]]

# dataframe of predictions from multiple rounds of CV: 
df.cv <- cross_validation(m, 
                          initial = 825, 
                          horizon = 7,
                          units = "days")

# Making 285 forecasts with cutoffs between 2016-09-23 and 2019-06-14

write_csv(df.cv,
          here::here("results", 
                     "output from src", 
                     "2019-07-04_cross-validate-prophet-model.csv"))
                         

# performance metrics 
df.performance <- performance_metrics(df.cv)

write_csv(df.performance,
          here::here("results", 
                     "output from src", 
                     "2019-07-04_performance-metrics-for-prophet-model.csv"))


```



\  
\  
\  

# Validating forecast with actual data: 



```{r}
# plot comparing actual with forecast: 
edvisits_fcast_df <- edvisits_fcast[[1]]

# plot 
edvisits_fcast_df %>%
      ggplot(aes(x = ds,
                 y = edvisits_fcast)) +
      geom_ribbon(aes(x = ds,
                      ymin = edvisits_lower_ci,
                      ymax = edvisits_upper_ci),
                  fill = "grey80",
                  alpha = 0.5) +
      geom_line(col = "skyblue") +
      geom_point(col = "skyblue") +

      geom_line(data = edvisits_actual %>% 
                      bind_cols(edvisits_fcast_df %>% select(ds)),
                aes(x = ds,
                    y = value),
                col = "blue") +

      theme_light() +
      theme(panel.grid.minor = element_line(colour = "grey95"),
              panel.grid.major = element_line(colour = "grey95"))

```

\    

# Holiday effects: 

```{r}
edvisits_fcast[[3]][[2]]
```

\  

```{r}
edvisits_fcast[[4]] %>% 
  select(ds,
         holidays) %>% 
  
  DT::datatable(extensions = 'Buttons', 
                options = list(dom = 'Bfrtip', 
                               buttons = c('excel', "csv"))) 
  
  

```

\  

